BASICS OF PYTORCH TENSORS

In [3]:
import torch
device='cpu'

In [20]:
my_tensor=torch.tensor([[1,2,3],[4,5,6],[7,8,9]] , dtype=torch.float32, device=device , requires_grad=True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], requires_grad=True)


In [24]:
import numpy as np
np_array = np.zeros((5, 5))
tensor = torch.from_numpy(np_array)
np_array_again = (tensor.numpy())
print(tensor)
print(np_array_again)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [27]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

z1 = torch.empty(3)  #default float32
torch.add(x, y, out=z1)  
z2 = torch.add(x, y)  
z = x + y  

tensor([10., 10., 10.])
tensor([10, 10, 10])
tensor([10, 10, 10])
torch.float32


In [48]:
z1=torch.rand(2,3)
z2=torch.rand(3,4)
print(z1)
print(z2)
print(z1.mm(z2)) #matrix mul

# -- Batch Matrix Multiplication --
batch = 32
n = 10
m = 20
p = 30
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2)  # Will be shape: (b x n x p)

tensor([[0.8367, 0.7189, 0.7569],
        [0.2746, 0.5310, 0.8185]])
tensor([[0.9956, 0.8710, 0.2525, 0.5232],
        [0.8993, 0.2138, 0.1536, 0.1682],
        [0.2754, 0.4256, 0.3458, 0.3414]])
tensor([[1.6880, 1.2046, 0.5835, 0.8171],
        [0.9763, 0.7010, 0.4339, 0.5124]])


In [128]:
x = torch.arange(10)
print(x)
print(torch.where(x > 5, x, x * 2))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])


In [139]:
z=torch.randint(1,10,(3,3,3))
print(z)
print(z.reshape(-1))  #flatten
print(z.reshape(3,-1))  #keep dim = 3 and flattens other dim

tensor([[[3, 7, 4],
         [9, 1, 5],
         [5, 7, 1]],

        [[6, 6, 5],
         [8, 2, 6],
         [2, 4, 9]],

        [[6, 4, 6],
         [9, 5, 4],
         [1, 2, 7]]])
tensor([3, 7, 4, 9, 1, 5, 5, 7, 1, 6, 6, 5, 8, 2, 6, 2, 4, 9, 6, 4, 6, 9, 5, 4,
        1, 2, 7])
tensor([[3, 7, 4, 9, 1, 5, 5, 7, 1],
        [6, 6, 5, 8, 2, 6, 2, 4, 9],
        [6, 4, 6, 9, 5, 4, 1, 2, 7]])


In [148]:
a=torch.rand(2,2,2)
print(a)
print()
print(a.permute(0,2,1))   #transpose  (interchanges changes dim=2 and dim=1  row and column )

print(a.permute(2,1,0))

tensor([[[0.8773, 0.0399],
         [0.1558, 0.1976]],

        [[0.8938, 0.8562],
         [0.5585, 0.2928]]])

tensor([[[0.8773, 0.1558],
         [0.0399, 0.1976]],

        [[0.8938, 0.5585],
         [0.8562, 0.2928]]])
tensor([[[0.8773, 0.8938],
         [0.1558, 0.5585]],

        [[0.0399, 0.8562],
         [0.1976, 0.2928]]])


In [182]:
x=torch.arange(10)
print(x)
print(x.shape)
x.unsqueeze_(1)   #add a dimension  
print(x.shape)    #add 10 rows
print(x)

y=torch.arange(10)
print(y)
print(y.shape)
y.unsqueeze_(0)   
print(y.shape)     #add 1 row
print(y)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([10])
torch.Size([10, 1])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([10])
torch.Size([1, 10])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
